name: Check docker image

on:
  schedule:
    - cron:  '0 4 * * *'
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:

      - name: Check if update available
        id: check
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: jenkins/inbound-agent:latest
          image: cadmi/jenkins-inbound-agent:latest

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
        if: steps.check.outputs.needs-updating == 'true'

      - name: Checkout
        uses: actions/checkout@v3
        if: steps.check.outputs.needs-updating == 'true'

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: cadmi/jenkins-inbound-agent:latest
        if: steps.check.outputs.needs-updating == 'true'
